### PR TITLE
Add save game path to README

### PR DESCRIPTION
**Pull request by samrocketman**
*  https://github.com/thewierdnut/endless-mobile/blob/android/source/Files.cpp#L140
* https://github.com/libsdl-org/SDL/blob/a26a4e9ee2be42dfdba455d7c0136b90f888dd0b/src/filesystem/android/SDL_sysfilesystem.c#L46
* https://wiki.libsdl.org/SDL_AndroidGetInternalStoragePath
* https://github.com/thewierdnut/endless-mobile/blob/cce5a37a4edf7b58ffdd9efafb0f85728bb78eff/android/app/build.gradle#L15

### CODE REVIEW

**Comment by thewierdnut** [comment]
I'm not sure that this path will remain consistent from device to device. I know it has changed in the past. 

It may be more accurate to say something like "Preference, save game, and plugin data" are stored in the app's internal storage path, as defined by SDL_GetPrefPath(). 

Why are you wanting to add this to the README?

**Comment by samrocketman** [comment]
This may not be the right path bc android user reported they cannot find it

**Comment by thewierdnut** [comment]
Where is this mysterious android user? 

I noticed that the f-droid issue reporting link was incorrect, though that should be fixed now.

**Comment by larrydewey** [comment]
@thewierdnut I can verify the path is not correct. The `com.github.thewierdnut.endless_mobile` directory does not exist under the expect `<device_here>/Android/data/`. Attempting to access `/data/data` is not possible unless you have rooted your phone. Re-installing the application erases the directory in question, and you lose saved game information (from sad experience).

**Comment by larrydewey** [comment]
| Where is this mysterious android user?

That would be me. :wave:

**Comment by thewierdnut** [comment]
I wouldn't expect it to wipe out the saved data. Did you install from fdroid or from one of the test debug builds posted here?

**Comment by larrydewey** [comment]
> I wouldn't expect it to wipe out the saved data. Did you install from fdroid or from one of the test debug builds posted here?

I installed it via fdroid. I would be happy to jump on a chat/call with you when/if you have time to debug it.

**Comment by thewierdnut** [comment]
There is only one build posted (so far), so I presume that you had to uninstall and reinstall the app. When you uninstall an android app, my understanding is that it wipes the app's internal persistent storage as well. It sounds like it is behaving as expected. 

What may be needed here is a way to export/import save games.

**Comment by larrydewey** [comment]
> There is only one build posted (so far), so I presume that you had to uninstall and reinstall the app. When you uninstall an android app, my understanding is that it wipes the app's internal persistent storage as well. It sounds like it is behaving as expected.

That is usually the case, yes. It was a last-ditch effort in an attempt to see if something went wrong during the installation. Creating a new pilot and creating a snapshot also has not created the directory in question.

> What may be needed here is a way to export/import save games.

That would definitely be a nice feature to have!

**Comment by thewierdnut** [comment]
So... as far as the README edit goes... I'm not sure how much knowing the path helps. You either have to a) have rooted your phone, or b) have a debug build installed, so that you can use the run-as command from the adb shell. 

Having said that, I'm not sure that I object in principle, I just don't know what it adds. If you still want it in the README, I'm ok with it, although I might add a caveat about the SDL_GetPrefPath()

**Comment by thewierdnut** [comment]
I've created issue #6 for some sort of save game solution

**Comment by samrocketman** [comment]
SDL_Android has a path for external storage

**Pull request closed without merging**
